export const elementosActinidos = [
  {
    simbolo: "Th",
    nombre: "Torio",
    numeroAtomico: 90,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Pa",
    nombre: "Protactinio",
    numeroAtomico: 91,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "U",
    nombre: "Uranio",
    numeroAtomico: 92,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Np",
    nombre: "Neptunio",
    numeroAtomico: 93,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Pu",
    nombre: "Plutonio",
    numeroAtomico: 94,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Am",
    nombre: "Americio",
    numeroAtomico: 95,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Cm",
    nombre: "Curio",
    numeroAtomico: 96,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Bk",
    nombre: "Berkelio",
    numeroAtomico: 97,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Cf",
    nombre: "Californio",
    numeroAtomico: 98,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Es",
    nombre: "Einstenio",
    numeroAtomico: 99,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Fm",
    nombre: "Fermio",
    numeroAtomico: 100,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Md",
    nombre: "Mendelevio",
    numeroAtomico: 101,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "No",
    nombre: "Nobelio",
    numeroAtomico: 102,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Lr",
    nombre: "Lawrencio",
    numeroAtomico: 103,
    tipo: "Actínido",
    color: "#c994d6",
  },
];
