export const elementosActinidos = [
  {
    simbolo: "Th",
    nombre: "Torio",
    numeroAtomico: 90,
    masaAtomica: 232.0377,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Pa",
    nombre: "Protactinio",
    numeroAtomico: 91,
    masaAtomica: 231.0359,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "U",
    nombre: "Uranio",
    numeroAtomico: 92,
    masaAtomica: 238.0289,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Np",
    nombre: "Neptunio",
    numeroAtomico: 93,
    masaAtomica: 237.0482,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Pu",
    nombre: "Plutonio",
    numeroAtomico: 94,
    masaAtomica: 244,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Am",
    nombre: "Americio",
    numeroAtomico: 95,
    masaAtomica: 243,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Cm",
    nombre: "Curio",
    numeroAtomico: 96,
    masaAtomica: 247,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Bk",
    nombre: "Berkelio",
    numeroAtomico: 97,
    masaAtomica: 247,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Cf",
    nombre: "Californio",
    numeroAtomico: 98,
    masaAtomica: 251,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Es",
    nombre: "Einstenio",
    numeroAtomico: 99,
    masaAtomica: 252,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Fm",
    nombre: "Fermio",
    numeroAtomico: 100,
    masaAtomica: 257,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Md",
    nombre: "Mendelevio",
    numeroAtomico: 101,
    masaAtomica: 258,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "No",
    nombre: "Nobelio",
    numeroAtomico: 102,
    masaAtomica: 259,
    tipo: "Actínido",
    color: "#c994d6",
  },
  {
    simbolo: "Lr",
    nombre: "Lawrencio",
    numeroAtomico: 103,
    masaAtomica: 262,
    tipo: "Actínido",
    color: "#c994d6",
  },
];
