export const elementosLantanidos = [
  {
    simbolo: "Ce",
    nombre: "Cerio",
    numeroAtomico: 58,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Pr",
    nombre: "Praseodimio",
    numeroAtomico: 59,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Nd",
    nombre: "Neodimio",
    numeroAtomico: 60,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Pm",
    nombre: "Prometio",
    numeroAtomico: 61,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Sm",
    nombre: "Samario",
    numeroAtomico: 62,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Eu",
    nombre: "Europio",
    numeroAtomico: 63,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Gd",
    nombre: "Gadolinio",
    numeroAtomico: 64,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Tb",
    nombre: "Terbio",
    numeroAtomico: 65,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Dy",
    nombre: "Disprosio",
    numeroAtomico: 66,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Ho",
    nombre: "Holmio",
    numeroAtomico: 67,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Er",
    nombre: "Erbio",
    numeroAtomico: 68,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Tm",
    nombre: "Tulio",
    numeroAtomico: 69,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Yb",
    nombre: "Iterbio",
    numeroAtomico: 70,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Lu",
    nombre: "Lutecio",
    numeroAtomico: 71,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
];
