export const elementos = [
  {
    simbolo: "H",
    nombre: "Hidrógeno",
    numeroAtomico: 1,
    masaAtomica: 1.008,
    grupo: 1,
    periodo: 1,
    color: "#728a9c",
  },
  {
    simbolo: "He",
    nombre: "Helio",
    numeroAtomico: 2,
    masaAtomica: 4.0026,
    grupo: 18,
    periodo: 1,
    color: "#7a568f",
  },
  {
    simbolo: "Li",
    nombre: "Litio",
    numeroAtomico: 3,
    masaAtomica: 6.94,
    grupo: 1,
    periodo: 2,
    color: "#de7254",
  },
  {
    simbolo: "Be",
    nombre: "Berilio",
    numeroAtomico: 4,
    masaAtomica: 9.0122,
    grupo: 2,
    periodo: 2,
    color: "#e39e30",
  },
  {
    simbolo: "B",
    nombre: "Boro",
    numeroAtomico: 5,
    masaAtomica: 10.81,
    grupo: 13,
    periodo: 2,
    color: "#5685d1",
  },
  {
    simbolo: "C",
    nombre: "Carbono",
    numeroAtomico: 6,
    masaAtomica: 12.011,
    grupo: 14,
    periodo: 2,
    color: "#728a9c",
  },
  {
    simbolo: "N",
    nombre: "Nitrogeno",
    numeroAtomico: 7,
    masaAtomica: 14.007,
    grupo: 15,
    periodo: 2,
    color: "#728a9c",
  },
  {
    simbolo: "O",
    nombre: "Oxigeno",
    numeroAtomico: 8,
    masaAtomica: 15.999,
    grupo: 16,
    periodo: 2,
    color: "#728a9c",
  },
  {
    simbolo: "F",
    nombre: "Fluor",
    numeroAtomico: 9,
    masaAtomica: 18.998,
    grupo: 17,
    periodo: 2,
    color: "#729c99",
  },
  {
    simbolo: "Ne",
    nombre: "Neon",
    numeroAtomico: 10,
    masaAtomica: 20.18,
    grupo: 18,
    periodo: 2,
    color: "#7a568f",
  },
  {
    simbolo: "Na",
    nombre: "Sodio",
    numeroAtomico: 11,
    masaAtomica: 22.99,
    grupo: 1,
    periodo: 3,
    color: "#de7254",
  },
  {
    simbolo: "Mg",
    nombre: "Magnesio",
    numeroAtomico: 12,
    masaAtomica: 24.305,
    grupo: 2,
    periodo: 3,
    color: "#e39e30",
  },
  {
    simbolo: "Al",
    nombre: "Aluminio",
    numeroAtomico: 13,
    masaAtomica: 26.982,
    grupo: 13,
    periodo: 3,
    color: "#4d9e77",
  },
  {
    simbolo: "Si",
    nombre: "Silicio",
    numeroAtomico: 14,
    masaAtomica: 28.085,
    grupo: 14,
    periodo: 3,
    color: "#5685d1",
  },
  {
    simbolo: "P",
    nombre: "Fósforo",
    numeroAtomico: 15,
    masaAtomica: 30.974,
    grupo: 15,
    periodo: 3,
    color: "#728a9c",
  },
  {
    simbolo: "S",
    nombre: "Azufre",
    numeroAtomico: 16,
    masaAtomica: 32.06,
    grupo: 16,
    periodo: 3,
    color: "#728a9c",
  },
  {
    simbolo: "Cl",
    nombre: "Cloro",
    numeroAtomico: 17,
    masaAtomica: 35.45,
    grupo: 17,
    periodo: 3,
    color: "#729c99",
  },
  {
    simbolo: "Ar",
    nombre: "Argón",
    numeroAtomico: 18,
    masaAtomica: 39.948,
    grupo: 18,
    periodo: 3,
    color: "#7a568f",
  },
  {
    simbolo: "K",
    nombre: "Potasio",
    numeroAtomico: 19,
    masaAtomica: 39.098,
    grupo: 1,
    periodo: 4,
    color: "#de7254",
  },
  {
    simbolo: "Ca",
    nombre: "Calcio",
    numeroAtomico: 20,
    masaAtomica: 40.078,
    grupo: 2,
    periodo: 4,
    color: "#e39e30",
  },
  {
    simbolo: "Sc",
    nombre: "Escandio",
    numeroAtomico: 21,
    masaAtomica: 44.956,
    grupo: 3,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Ti",
    nombre: "Titanio",
    numeroAtomico: 22,
    masaAtomica: 47.867,
    grupo: 4,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "V",
    nombre: "Vanadio",
    numeroAtomico: 23,
    masaAtomica: 50.942,
    grupo: 5,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Cr",
    nombre: "Cromo",
    numeroAtomico: 24,
    masaAtomica: 52.037,
    grupo: 6,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Mn",
    nombre: "Manganeso",
    numeroAtomico: 25,
    masaAtomica: 54.938,
    grupo: 7,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Fe",
    nombre: "Hierro",
    numeroAtomico: 26,
    masaAtomica: 55.845,
    grupo: 8,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Co",
    nombre: "Cobalto",
    numeroAtomico: 27,
    masaAtomica: 58.933,
    grupo: 9,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Ni",
    nombre: "Niquel",
    numeroAtomico: 28,
    masaAtomica: 58.693,
    grupo: 10,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Cu",
    nombre: "Cobre",
    numeroAtomico: 29,
    masaAtomica: 63.546,
    grupo: 11,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Zn",
    nombre: "Zinc",
    numeroAtomico: 30,
    masaAtomica: 65.38,
    grupo: 12,
    periodo: 4,
    color: "#e6c730",
  },
  {
    simbolo: "Ga",
    nombre: "Galio",
    numeroAtomico: 31,
    masaAtomica: 69.723,
    grupo: 13,
    periodo: 4,
    color: "#4d9e77",
  },
  {
    simbolo: "Ge",
    nombre: "Germanio",
    numeroAtomico: 32,
    masaAtomica: 72.63,
    grupo: 14,
    periodo: 4,
    color: "#5685d1",
  },
  {
    simbolo: "As",
    nombre: "Arsénico",
    numeroAtomico: 33,
    masaAtomica: 74.922,
    grupo: 15,
    periodo: 4,
    color: "#5685d1",
  },
  {
    simbolo: "Se",
    nombre: "Selenio",
    numeroAtomico: 34,
    masaAtomica: 78.971,
    grupo: 16,
    periodo: 4,
    color: "#728a9c",
  },
  {
    simbolo: "Br",
    nombre: "Bromo",
    numeroAtomico: 35,
    masaAtomica: 79.904,
    grupo: 17,
    periodo: 4,
    color: "#729c99",
  },
  {
    simbolo: "Kr",
    nombre: "Kriptón",
    numeroAtomico: 36,
    masaAtomica: 83.798,
    grupo: 18,
    periodo: 4,
    color: "#7a568f",
  },
  {
    simbolo: "Rb",
    nombre: "Rubidio",
    numeroAtomico: 37,
    masaAtomica: 85.468,
    grupo: 1,
    periodo: 5,
    color: "#de7254",
  },
  {
    simbolo: "Sr",
    nombre: "Estroncio",
    numeroAtomico: 38,
    masaAtomica: 87.62,
    grupo: 2,
    periodo: 5,
    color: "#e39e30",
  },
  {
    simbolo: "Y",
    nombre: "Itrio",
    numeroAtomico: 39,
    masaAtomica: 88.906,
    grupo: 3,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Zr",
    nombre: "Circonio",
    numeroAtomico: 40,
    masaAtomica: 91.224,
    grupo: 4,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Nb",
    nombre: "Niobio",
    numeroAtomico: 41,
    masaAtomica: 92.906,
    grupo: 5,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Mo",
    nombre: "Molibdeno",
    numeroAtomico: 42,
    masaAtomica: 95.95,
    grupo: 6,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Tc",
    nombre: "Tecnecio",
    numeroAtomico: 43,
    masaAtomica: 98,
    grupo: 7,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Ru",
    nombre: "Rutenio",
    numeroAtomico: 44,
    masaAtomica: 101.07,
    grupo: 8,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Rh",
    nombre: "Rodio",
    numeroAtomico: 45,
    masaAtomica: 102.91,
    grupo: 9,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Pd",
    nombre: "Paladio",
    numeroAtomico: 46,
    masaAtomica: 106.42,
    grupo: 10,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Ag",
    nombre: "Plata",
    numeroAtomico: 47,
    masaAtomica: 107.87,
    grupo: 11,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "Cd",
    nombre: "Cadmio",
    numeroAtomico: 48,
    masaAtomica: 112.41,
    grupo: 12,
    periodo: 5,
    color: "#e6c730",
  },
  {
    simbolo: "In",
    nombre: "Indio",
    numeroAtomico: 49,
    masaAtomica: 114.82,
    grupo: 13,
    periodo: 5,
    color: "#4d9e77",
  },
  {
    simbolo: "Sn",
    nombre: "Estaño",
    numeroAtomico: 50,
    masaAtomica: 118.71,
    grupo: 14,
    periodo: 5,
    color: "#4d9e77",
  },
  {
    simbolo: "Sb",
    nombre: "Antimonio",
    numeroAtomico: 51,
    masaAtomica: 121.76,
    grupo: 15,
    periodo: 5,
    color: "#5685d1",
  },
  {
    simbolo: "Te",
    nombre: "Telurio",
    numeroAtomico: 52,
    masaAtomica: 127.6,
    grupo: 16,
    periodo: 5,
    color: "#5685d1",
  },
  {
    simbolo: "I",
    nombre: "Yodo",
    numeroAtomico: 53,
    masaAtomica: 126.9,
    grupo: 17,
    periodo: 5,
    color: "#729c99",
  },
  {
    simbolo: "Xe",
    nombre: "Xenón",
    numeroAtomico: 54,
    masaAtomica: 131.29,
    grupo: 18,
    periodo: 5,
    color: "#7a568f",
  },
  {
    simbolo: "Cs",
    nombre: "Cesio",
    numeroAtomico: 55,
    masaAtomica: 132.91,
    grupo: 1,
    periodo: 6,
    color: "#de7254",
  },
  {
    simbolo: "Ba",
    nombre: "Bario",
    numeroAtomico: 56,
    masaAtomica: 137.33,
    grupo: 2,
    periodo: 6,
    color: "#e39e30",
  },
  {
    simbolo: "La",
    nombre: "Lantano",
    numeroAtomico: 57,
    masaAtomica: 138.91,
    grupo: 3,
    periodo: 6,
    color: "#bd77b6",
  },
  {
    simbolo: "Hf",
    nombre: "Hafnio",
    numeroAtomico: 72,
    masaAtomica: 178.49,
    grupo: 4,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Ta",
    nombre: "Tántalo",
    numeroAtomico: 73,
    masaAtomica: 180.95,
    grupo: 5,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "W",
    nombre: "Wolframio",
    numeroAtomico: 74,
    masaAtomica: 183.84,
    grupo: 6,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Re",
    nombre: "Renio",
    numeroAtomico: 75,
    masaAtomica: 186.21,
    grupo: 7,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Os",
    nombre: "Osmio",
    numeroAtomico: 76,
    masaAtomica: 190.23,
    grupo: 8,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Ir",
    nombre: "Iridio",
    numeroAtomico: 77,
    masaAtomica: 192.22,
    grupo: 9,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Pt",
    nombre: "Platino",
    numeroAtomico: 78,
    masaAtomica: 195.08,
    grupo: 10,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Au",
    nombre: "Oro",
    numeroAtomico: 79,
    masaAtomica: 196.97,
    grupo: 11,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Hg",
    nombre: "Mercurio",
    numeroAtomico: 80,
    masaAtomica: 200.59,
    grupo: 12,
    periodo: 6,
    color: "#e6c730",
  },
  {
    simbolo: "Tl",
    nombre: "Talio",
    numeroAtomico: 81,
    masaAtomica: 204.38,
    grupo: 13,
    periodo: 6,
    color: "#4d9e77",
  },
  {
    simbolo: "Pb",
    nombre: "Plomo",
    numeroAtomico: 82,
    masaAtomica: 207.2,
    grupo: 14,
    periodo: 6,
    color: "#4d9e77",
  },
  {
    simbolo: "Bi",
    nombre: "Bismuto",
    numeroAtomico: 83,
    masaAtomica: 208.98,
    grupo: 15,
    periodo: 6,
    color: "#4d9e77",
  },
  {
    simbolo: "Po",
    nombre: "Polonio",
    numeroAtomico: 84,
    masaAtomica: 209,
    grupo: 16,
    periodo: 6,
    color: "#5685d1",
  },
  {
    simbolo: "At",
    nombre: "Astato",
    numeroAtomico: 85,
    masaAtomica: 210,
    grupo: 17,
    periodo: 6,
    color: "#729c99",
  },
  {
    simbolo: "Rn",
    nombre: "Radón",
    numeroAtomico: 86,
    masaAtomica: 222,
    grupo: 18,
    periodo: 6,
    color: "#7a568f",
  },
  {
    simbolo: "Fr",
    nombre: "Francio",
    numeroAtomico: 87,
    masaAtomica: 223,
    grupo: 1,
    periodo: 7,
    color: "#de7254",
  },
  {
    simbolo: "Ra",
    nombre: "Radio",
    numeroAtomico: 88,
    masaAtomica: 226.03,
    grupo: 2,
    periodo: 7,
    color: "#e39e30",
  },
  {
    simbolo: "Ac",
    nombre: "Actinio",
    numeroAtomico: 89,
    masaAtomica: 227,
    grupo: 3,
    periodo: 7,
    color: "#c994d6",
  },
  {
    simbolo: "Rf",
    nombre: "Rutherfordio",
    numeroAtomico: 104,
    masaAtomica: 267,
    grupo: 4,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Db",
    nombre: "Dubnio",
    numeroAtomico: 105,
    masaAtomica: 270,
    grupo: 5,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Sg",
    nombre: "Seaborgio",
    numeroAtomico: 106,
    masaAtomica: 271,
    grupo: 6,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Bh",
    nombre: "Bohrio",
    numeroAtomico: 107,
    masaAtomica: 270,
    grupo: 7,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Hs",
    nombre: "Hasio",
    numeroAtomico: 108,
    masaAtomica: 277,
    grupo: 8,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Mt",
    nombre: "Meitnerio",
    numeroAtomico: 109,
    masaAtomica: 276,
    grupo: 9,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Ds",
    nombre: "Darmstatio",
    numeroAtomico: 110,
    masaAtomica: 281,
    grupo: 10,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Rg",
    nombre: "Roentgenio",
    numeroAtomico: 111,
    masaAtomica: 280,
    grupo: 11,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Cn",
    nombre: "Copernicio",
    numeroAtomico: 112,
    masaAtomica: 285,
    grupo: 12,
    periodo: 7,
    color: "#e6c730",
  },
  {
    simbolo: "Nh",
    nombre: "Nihonio",
    numeroAtomico: 113,
    masaAtomica: 284,
    grupo: 13,
    periodo: 7,
    color: "#4d9e77",
  },
  {
    simbolo: "Fl",
    nombre: "Flerovio",
    numeroAtomico: 114,
    masaAtomica: 289,
    grupo: 14,
    periodo: 7,
    color: "#4d9e77",
  },
  {
    simbolo: "Mc",
    nombre: "Moscovio",
    numeroAtomico: 115,
    masaAtomica: 288,
    grupo: 15,
    periodo: 7,
    color: "#4d9e77",
  },
  {
    simbolo: "Lv",
    nombre: "Livermorio",
    numeroAtomico: 116,
    masaAtomica: 293,
    grupo: 16,
    periodo: 7,
    color: "#4d9e77",
  },
  {
    simbolo: "Ts",
    nombre: "Teneso",
    numeroAtomico: 117,
    masaAtomica: 294,
    grupo: 17,
    periodo: 7,
    color: "#729c99",
  },
  {
    simbolo: "Og",
    nombre: "Oganesón",
    numeroAtomico: 118,
    masaAtomica: 294,
    grupo: 18,
    periodo: 7,
    color: "#7a568f",
  },
];
