export const elementosLantanidos = [
  {
    simbolo: "Ce",
    nombre: "Cerio",
    numeroAtomico: 58,
    masaAtomica: 140.116,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Pr",
    nombre: "Praseodimio",
    numeroAtomico: 59,
    masaAtomica: 140.9077,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Nd",
    nombre: "Neodimio",
    numeroAtomico: 60,
    masaAtomica: 144.242,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Pm",
    nombre: "Prometio",
    numeroAtomico: 61,
    masaAtomica: 145,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Sm",
    nombre: "Samario",
    numeroAtomico: 62,
    masaAtomica: 150.36,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Eu",
    nombre: "Europio",
    numeroAtomico: 63,
    masaAtomica: 151.964,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Gd",
    nombre: "Gadolinio",
    numeroAtomico: 64,
    masaAtomica: 157.25,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Tb",
    nombre: "Terbio",
    numeroAtomico: 65,
    masaAtomica: 158.925,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Dy",
    nombre: "Disprosio",
    numeroAtomico: 66,
    masaAtomica: 162.5,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Ho",
    nombre: "Holmio",
    numeroAtomico: 67,
    masaAtomica: 164.9303,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Er",
    nombre: "Erbio",
    numeroAtomico: 68,
    masaAtomica: 167.259,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Tm",
    nombre: "Tulio",
    numeroAtomico: 69,
    masaAtomica: 168.9342,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Yb",
    nombre: "Iterbio",
    numeroAtomico: 70,
    masaAtomica: 173.04,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
  {
    simbolo: "Lu",
    nombre: "Lutecio",
    numeroAtomico: 71,
    masaAtomica: 174.9668,
    tipo: "Lantánido",
    color: "#bd77b6",
  },
];
